contact form
solog0039/mobile-version1 pull request #2
Opened 2022-05-31 20:50 UTC by solog0039

In this project
1. GitHub workflow added
2. linters installed
3. contact form completed

2022-05-31 21:08 UTC, koachcode requested changes
Hi @solog0039 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- Linter all green :+1: 
- Good code structure :100: 
- - Good PR nameing :100: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 21:08 UTC, koachcode commented on index.html
> +        </form>
- Please make use of the appropriate font size as it is on the Figma design and center the text so it looks like that of the Figma design. i meant the `<p>` with the text  `I'm always interested in hearing about new projects, so if you'd like to chat please get in touch
- Please the button Get in touch should have the proper padding as it is on the Figma design.
##### Figma Design 
![Screenshot from 2022-05-31 21-58-21](https://user-images.githubusercontent.com/58771507/171283793-ea0a65a4-f6f6-4e85-9f5a-0b3435da351f.png)

##### Your Design 
![Screenshot from 2022-05-31 21-58-04](https://user-images.githubusercontent.com/58771507/171283837-e4a0cfb1-a7a5-4899-b437-50552aa9643d.png)

2022-05-31 21:08 UTC, koachcode commented on index.html
> +            <img class="angel" src="form-image/angel.png" alt="angelist">
- Please use a better icon on the `Linkedin` icon as it looks fade, or you can increase the opacity, if it was initially reduced, so as to look like that of the Figma design.
##### Figma design 
![Screenshot from 2022-05-31 22-04-30](https://user-images.githubusercontent.com/58771507/171284226-dacfb9ac-ff49-4210-82c6-1f3473ee4f33.png)

##### Your design
![Screenshot from 2022-05-31 22-04-13](https://user-images.githubusercontent.com/58771507/171284212-e9c274e9-b86a-4c28-8f7e-73e19d2c0c92.png)

2022-05-31 21:08 UTC, koachcode commented on index.html
> +                name="usrmessage">
- Please make this a type of `textarea` and not a type of `text`, so as to make your HTML  more semantically correct.

2022-05-31 22:02 UTC, solog0039 commented on index.html
> +            <img class="angel" src="form-image/angel.png" alt="angelist">
Dear @Ginohmk I can not get LinkedIn icon like in the figma. The icon in the figma is separated in to i and n. so I will keep as it is or please let me know if the is another option

2022-05-31 22:17 UTC, solog0039 commented on index.html
> +                name="usrmessage">
![Capture](https://user-images.githubusercontent.com/99722854/171293322-8e2286ae-8123-4c1d-849e-0fc358fa57be.PNG)

2022-06-01 00:07 UTC, Kakalanp requested changes
# STATUS: Changes required :exclamation: 

### Hello there @solog0039! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28px" alt="hi">

### Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. :memo: 

<img src="https://media.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized.gif" alt="almost there">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:
- Excellent communication with CRs' :monocle_face: 

 ## Required Changes ♻️
***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 00:07 UTC, Kakalanp commented on index.html
> +            <img class="angel" src="form-image/angel.png" alt="angelist">
- If I'm not mistaken, you can select both and [export them](https://help.figma.com/hc/en-us/articles/360040028114-Guide-to-exports-in-Figma) as a png :bulb: 

- Another solution could be to use a service like [icons8](https://icons8.com/) and look for a LinkedIn icon there :smiley:

2022-06-01 00:07 UTC, Kakalanp commented on index.html
> +        </form>
You could set your `font-weight to 34px to fix this issue, that worked on my end :grin:

2022-06-01 00:07 UTC, Kakalanp commented on index.html
> +                name="usrmessage">
I apologize for the mistake, the previous CR meant that you change the HTML tag from `<input>` to [`<textarea>`](https://www.w3schools.com/tags/tag_textarea.asp#:~:text=Definition%20and%20Usage,width%20font%20(usually%20Courier).), as its name states, this is an **area** of **text**, so we should try to use this tag to follow best practices :wink:

2022-06-01 16:07 UTC, danmainah approved these changes
Hi @solog0039 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 16:07 UTC, danmainah commented on README.md
> +#Portfolio-mobile-version
- [ ] [OPTIONAL] Kindly check the alignment in your Authors section;
![image](https://user-images.githubusercontent.com/61408860/171449632-be6f5465-98da-46e5-8e1a-a55614ec1d9a.png)

2022-06-01 17:01 UTC, merged